In [32]:
# import libraries
import pandas as pd
import seaborn as sns

In [33]:
#Load Dataset
df = pd.read_csv("01_insurance.csv")

In [34]:
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [35]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [36]:
# independent features
X = df.drop('charges', axis = 1)

#dependent feature
y = df['charges']

In [37]:
X.head()

   age     sex     bmi  children smoker     region
0   19  female  27.900         0    yes  southwest
1   18    male  33.770         1     no  southeast
2   28    male  33.000         3     no  southeast
3   33    male  22.705         0     no  northwest
4   32    male  28.880         0     no  northwest

# Feature Engineering

## 1) Mapping catagorical values to numerical values

In [38]:
# used when there only two values for feature 
X["sex"] = X["sex"].map({"female":0,"male":1})
X["smoker"] = X["smoker"].map({"yes":1, "no":0})

X.head()

   age  sex     bmi  children  smoker     region
0   19    0  27.900         0       1  southwest
1   18    1  33.770         1       0  southeast
2   28    1  33.000         3       0  southeast
3   33    1  22.705         0       0  northwest
4   32    1  28.880         0       0  northwest

## 1) One hot encoding
 - pd.get_dummies(X, columns=[''], drop_first= Flase)

- region feature has 4 regions , covert it into 4 columns(3 after dummy trap) and values to numbers for better model training

In [39]:
# region feature have 4 values so we do one hot encoding

X = pd.get_dummies(X, columns=['region'], drop_first=False, dtype=int)
X.head()

,age,sex,bmi,children,smoker,region_northeast,region_northwest,region_southeast,region_southwest
0,19,0,27.900,0,1,0,0,0,1
1,18,1,33.770,1,0,0,0,1,0
2,28,1,33.000,3,0,0,0,1,0
3,33,1,22.705,0,0,0,1,0,0
4,32,1,28.880,0,0,0,1,0,0

In [41]:
#Train test split 
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=42)

#intialize model
from sklearn.linear_model import LinearRegression

model = LinearRegression()

#train model
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

In [47]:
# Evaluation
from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_pred)
print(r2)

0.7835929767120723

In [ ]:
# r2 score increased from 
#0.7811302113434097 to 0.7835929767120723