In [151]:
import pandas as pd

In [152]:
df = pd.read_csv("02_HousePricePrediction.csv")

In [153]:

df.head()

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.0
1,1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.0
2,2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.0
3,3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.0
4,4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.0

In [154]:
# Data Preprocessing - Data Cleaning

#drop Id column as it doesnt contribute
df.drop(['Id'], axis=1, inplace=True )

In [155]:
# checki for null values
df.isnull().sum()

MSSubClass         0
MSZoning           4
LotArea            0
LotConfig          0
BldgType           0
OverallCond        0
YearBuilt          0
YearRemodAdd       0
Exterior1st        1
BsmtFinSF2         1
TotalBsmtSF        1
SalePrice       1459
dtype: int64

In [156]:
#replace null SalePrice with mean
df['SalePrice'] = df['SalePrice'].fillna(df['SalePrice'].mean())

# remove other records(rows) with null values
df = df.dropna()

In [157]:
df.isnull().sum()
df.head()

,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.0
1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.0
2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.0
3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.0
4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.0

In [158]:
# data preprocessing - Encoding Features
cols = ['MSZoning','LotConfig', 'BldgType', 'Exterior1st']
df = pd.get_dummies(df, columns=cols, drop_first = True, dtype=int)

In [159]:
df.sample(10)

,MSSubClass,LotArea,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF2,TotalBsmtSF,SalePrice,MSZoning_FV,MSZoning_RH,...,Exterior1st_CemntBd,Exterior1st_HdBoard,Exterior1st_ImStucc,Exterior1st_MetalSd,Exterior1st_Plywood,Exterior1st_Stone,Exterior1st_Stucco,Exterior1st_VinylSd,Exterior1st_Wd Sdng,Exterior1st_WdShing
1009,50,6000,5,1926,1950,0.0,1008.0,102000.00000,0,0,...,0,0,0,0,0,0,0,0,1,0
2473,50,10320,1,1910,1950,0.0,771.0,180921.19589,0,0,...,0,0,0,0,0,0,0,0,1,0
1123,20,9405,9,1947,2008,0.0,698.0,118000.00000,0,0,...,0,0,0,0,0,0,0,1,0,0
1436,20,9000,6,1971,1971,0.0,864.0,120500.00000,0,0,...,0,1,0,0,0,0,0,0,0,0
2068,20,10122,6,1948,1950,0.0,0.0,180921.19589,0,0,...,0,0,0,1,0,0,0,0,0,0
2132,30,7200,7,1925,1992,0.0,1040.0,180921.19589,0,0,...,0,0,0,0,0,0,0,1,0,0
1468,20,10176,5,1990,1990,0.0,1300.0,180921.19589,0,0,...,0,1,0,0,0,0,0,0,0,0
2279,20,17199,7,1961,1961,0.0,914.0,180921.19589,0,0,...,0,0,0,1,0,0,0,0,0,0
1168,70,13728,7,1935,1986,0.0,1127.0,235000.00000,0,0,...,0,0,0,0,0,0,1,0,0,0
1525,190,13587,5,1958,1958,0.0,988.0,180921.19589,0,0,...,0,0,0,1,0,0,0,0,0,0

In [160]:
# Train Test Split
from sklearn.model_selection import train_test_split

X = df.drop(['SalePrice'], axis=1)
y = df['SalePrice']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [162]:
X_train.head()

,MSSubClass,LotArea,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF2,TotalBsmtSF,MSZoning_FV,MSZoning_RH,MSZoning_RL,...,Exterior1st_CemntBd,Exterior1st_HdBoard,Exterior1st_ImStucc,Exterior1st_MetalSd,Exterior1st_Plywood,Exterior1st_Stone,Exterior1st_Stucco,Exterior1st_VinylSd,Exterior1st_Wd Sdng,Exterior1st_WdShing
2356,20,7441,5,2006,2006,0.0,1461.0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
1789,30,10800,5,1890,1998,0.0,630.0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
2371,20,7321,5,1999,2000,0.0,1339.0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
930,20,8925,5,2007,2007,0.0,1466.0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
2816,20,13050,6,1963,1963,850.0,1000.0,0,0,1,...,0,0,0,0,0,0,0,0,0,1

In [163]:
# Train Linear Regression Model
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [165]:
y_pred = model.predict(X_test)

In [164]:
# Evaluate Metrics
from sklearn.metrics import r2_score